# Exported from Render on 2024-09-25T02:48:28Z
services:
  - type: web
    name: avatarapp
    runtime: ruby
    repo: https://github.com/Lainuz/avatarapp
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
    region: oregon
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake
      assets:clean;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
version: "1"
